
server:
  port: 82

spring:
  datasource:
    url: jdbc:mysql://42.192.15.218:3306/glorious?useUnicode=true&characterEncoding=gbk&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: qiong
    password: qiong
  redis:
    host: 42.192.15.218
    port: 6379
  rabbitmq:
    host: 42.192.15.218
    port: 5672
    virtual-host: glorious
    username: qiong
    password: qiong

logging:
  level:
    # com.glorious.model: debug
    com.glorious.system: debug
    com.glorious.framework: debug

mybatis-plus:
  configuration:
    # log-impl: org.apache.ibatis.logging.stdout.StdOutImpl