
server:
  port: 82

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/glorious?useUnicode=true&characterEncoding=gbk&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: qiong
    password: qiong
  redis:
    host: 127.0.0.1
    port: 6379
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    virtual-host: glorious
    username: qiong
    password: qiong
